# Generated by Django 5.1.4 on 2024-12-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
